Update collect.yaml

diff --git a/.github/workflows/collect.yaml b/.github/workflows/collect.yaml
--- a/.github/workflows/collect.yaml
+++ b/.github/workflows/collect.yaml
@@ -66,6 +66,10 @@ jobs:
 
       - name: Collect
         run: python -u subscribe/collect.py --all --overwrite --skip
+         if [ $? -ne 0 ]; then
+          echo "Collect step failed"
+          exit 1
+         fi
 
       - name: Timestamp
         run: date
